usage: main.py [-h] [--train_dir TRAIN_DIR] [--val_dir VAL_DIR]
               [--img_size IMG_SIZE] [--modality_type {rnflt,bscan}]
               [--task {tds}] [--depth DEPTH] [--train_batch TRAIN_BATCH]
               [--valid_batch VALID_BATCH] [--num_workers NUM_WORKERS]
               [--epochs EPOCHS] [--val_interval VAL_INTERVAL] [--lr LR]
               [--transform {vit,cnn,albumentations,none}]
               [--save_dir SAVE_DIR] [--log_dir LOG_DIR] [--gpus GPUS]
               [--device DEVICE] [--patience PATIENCE]
main.py: error: unrecognized arguments:  
usage: main.py [-h] [--train_dir TRAIN_DIR] [--val_dir VAL_DIR]
               [--img_size IMG_SIZE] [--modality_type {rnflt,bscan}]
               [--task {tds}] [--depth DEPTH] [--train_batch TRAIN_BATCH]
               [--valid_batch VALID_BATCH] [--num_workers NUM_WORKERS]
               [--epochs EPOCHS] [--val_interval VAL_INTERVAL] [--lr LR]
               [--transform {vit,cnn,albumentations,none}]
               [--save_dir SAVE_DIR] [--log_dir LOG_DIR] [--gpus GPUS]
               [--device DEVICE] [--patience PATIENCE]
main.py: error: unrecognized arguments:  
Traceback (most recent call last):
  File "/mnt/sda/sijiali/GlaucomaCode/main.py", line 4, in <module>
    from utils import get_vit_transform, get_cnn_transform, get_albumentations_transform
  File "/mnt/sda/sijiali/GlaucomaCode/utils.py", line 4, in <module>
    from monai.transforms import Compose, ResizeD, ScaleIntensityRangeD, ToTensord, NormalizeIntensityd
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/site-packages/monai/__init__.py", line 104, in <module>
    load_submodules(sys.modules[__name__], True, exclude_pattern=excludes)
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/site-packages/monai/utils/module.py", line 187, in load_submodules
    mod = import_module(name)
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/site-packages/monai/apps/reconstruction/fastmri_reader.py", line 25, in <module>
    h5py, has_h5py = optional_import("h5py")
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/site-packages/monai/utils/module.py", line 378, in optional_import
    pkg = __import__(module)  # top level module
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
  File "h5py/h5t.pyx", line 41, in init h5py.h5t
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/platform.py", line 806, in __getitem__
    return tuple(iter(self))[key]
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/platform.py", line 802, in __iter__
    (self.processor,)
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/platform.py", line 797, in processor
    return _unknown_as_blank(_Processor.get())
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/platform.py", line 749, in get
    return func() or ''
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/platform.py", line 768, in from_subprocess
    return subprocess.check_output(
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sijiali/anaconda3/envs/glaucoma/lib/python3.9/subprocess.py", line 1775, in _execute_child
    part = os.read(errpipe_read, 50000)
KeyboardInterrupt
[LAUNCH] GROUP:0  --gpus 0,1,2  LR:1e-5
[LAUNCH] GROUP:1  --gpus 3,4,5  LR:5e-5
[LAUNCH] GROUP:0  --gpus 0,1,2  LR:7e-5
[LAUNCH] GROUP:1  --gpus 3,4,5  LR:3e-4
[LAUNCH] GROUP:0  --gpus 0,1,2  LR:5e-4
[LAUNCH] GROUP:1  --gpus 3,4,5  LR:7e-4
All 6 runs completed (concurrency=2, 3 GPUs per run).
[LAUNCH] GROUP:0  --gpus 0,1,2  LR:5e-5
[LAUNCH] GROUP:1  --gpus 3,4,5  LR:5e-4
[LAUNCH] GROUP:1  --gpus 3,4,5  LR:1e-3
[LAUNCH] GROUP:1  --gpus 3,4,5  LR:5e-3
[LAUNCH] GROUP:1  --gpus 3,4,5  LR:1e-2
All 5 runs completed (concurrency=2, 3 GPUs per run).
